function calculoMedia(n1, n2, n3) {
    var media;
    var n1 = getElementById('n1').value;
    var n2 = getElementById('n2').value;
    var n3 = getElementById('n3').value;

    media = (n + n)/ n
    media1 = (n1 + n2) / 2;
    media2 = (n1 + n2 + n3) / 3;
    prompt("A média dos valores é: " + media + "");
  }

//A média entre dois números, é a soma dos dois números divididos por 2
//A média entre três números, é a some dos três números divididos por 3
//A média entre 'n' números, é a some dos 'n' números divididos por 'n'